defaults:
  - /base_factory
  - dataset: kaist_urban
  - _self_

regime:
  name: "TimeLimit"
  # Urban-27
  start: 1544582787831029719
  stop: 1544582797862356000

batch_memory_percent: 90.0

# 6 secs movement
