# type of map: "pose_graph" or "landmark_graph"
map_type: "pose_graph"

# logging properties  
logging : { use_logging: true,
            use_warnings: true,
            use_debug: true,
            log_directory: "./log"}

# these sensors are supported by the system:
supported_sensors: ["rgb_camera", "depth_camera", "imu", "wheel_encoder", "lidar", "gnss", "radar"] 

# sensors to be used: name-type
sensors : { imu1: imu,
            imu2: imu,
            camera1: rgb_camera,
            camera2: depth_camera}     