defaults:
  - /handlers/base_vrs_gps_preprocessor@handlers.vrs_gps_preprocessor
  - /handlers/base_kiss_icp_odometry@handlers.kiss_icp_odometry_1
  - /handlers/base_kiss_icp_odometry@handlers.kiss_icp_odometry_2

handlers:

  kiss_icp_odometry_1:
    name: "kiss_icp_odometry_1"
    type_name: "ScanMatcher"
    module_name: ".pointcloud_matcher"
    measurement_noise_covariance: [ 1, 1, 1, 1, 1, 1 ]

  kiss_icp_odometry_2:
    name: "kiss_icp_odometry_2"
    type_name: "ScanMatcher"
    module_name: ".pointcloud_matcher"
    measurement_noise_covariance: [ 1, 1, 1, 1, 1, 1 ]

  imu_preprocessor:
    name: "imu_preprocessor"
    type_name: "ImuDataPreprocessor"
    module_name: ".imu_data_preprocessor"


  vrs_gps_preprocessor:
    name: "vrs_gps_preprocessor"
    type_name: "VrsGpsPreprocessor"
    module_name: ".vrs_gps"
    fix_statuses: [ 4 ]
