defaults:
  - 2_lidar_odometry
  - /handlers/base_vrs_gps_preprocessor@handlers.vrs_gps_preprocessor

handlers:
  kiss_icp_odometry_1:
    name: "kiss_icp_odometry_1"
    type_name: "ScanMatcher"
    module_name: ".pointcloud_matcher"
    measurement_noise_covariance: [ 2, 2, 2, 2, 2, 2 ]

  kiss_icp_odometry_2:
    name: "kiss_icp_odometry_2"
    type_name: "ScanMatcher"
    module_name: ".pointcloud_matcher"
    measurement_noise_covariance: [ 2, 2, 2, 2, 2, 2 ]

  vrs_gps_preprocessor:
    name: "vrs_gps_preprocessor"
    type_name: "VrsGpsPreprocessor"
    module_name: ".vrs_gps"
    fix_statuses: [ 4 ]
