defaults:
  - lidar_odometry
  - /handlers/base_vrs_gps_preprocessor@handlers.vrs_gps_preprocessor
  - /handlers/base_kiss_icp_odometry@handlers.kiss_icp_odometry

handlers:

  vrs_gps_preprocessor:
    name: "vrs_gps_preprocessor"
    type_name: "VrsGpsPreprocessor"
    module_name: ".vrs_gps"
    fix_statuses: [ 4 ]

  kiss_icp_odometry:
    measurement_noise_covariance: [ 2, 2, 2, 2, 2, 2 ]
    min_range: 5.0
