defaults:
  - /handlers/base_kiss_icp_odometry@handlers.kiss_icp_odometry

handlers:
  kiss_icp_odometry:
    name: "kiss_icp_odometry"
    type_name: "ScanMatcher"
    module_name: ".pointcloud_matcher"
    measurement_noise_covariance: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]
    min_range: 3.0

package_name: 'slam.frontend_manager.handlers'
