defaults:
  - /handlers/base_visual_odometry@handlers.smart_visual_features

package_name: 'moduslam.frontend_manager.handlers'

handlers:
  visual_odometry:
    name: "smart_visual_features"
    type_name: "VisualOdometry"
    module_name: ".smart_visual_features.odometry_generator"

  imu_preprocessor:
    name: "imu_preprocessor"
    type_name: "ImuDataPreprocessor"
    module_name: ".imu_data_preprocessor"
