defaults:
  - /handlers/base_visual_odometry@handlers.keypoint_detector

package_name: 'moduslam.frontend_manager.handlers'

handlers:
  keypoint_detector:
    name: "keypoint_detector"
    type_name: "FeatureDetector"
    module_name: ".keypoint_detector.handler"
