defaults:
  - /handlers/base_visual_odometry@handlers.visual_odometry

package_name: 'moduslam.frontend_manager.handlers'

handlers:
  visual_odometry:
    name: "visual_odometry"
    type_name: "VisualOdometry"
    module_name: ".visual_odometry.odometry_generator"
    skip_n_frames: 0

  imu_preprocessor:
    name: "imu_preprocessor"
    type_name: "ImuDataPreprocessor"
    module_name: ".imu_data_preprocessor"
