defaults:
  - lidar_odometry

edge_factories:

  imu_odometry_edge_factory:
    name: 'imu_odometry_edge_factory'
    type_name: 'ImuOdometryFactory'
    module_name: '.imu_preintegration.imu_odometry_factory'
    search_time_margin: 0.01
