package_name: 'moduslam.frontend_manager.edge_factories'

edge_factories:

  prior_pose_edge_factory:
    name: 'prior_pose_edge_factory'
    type_name: 'PriorPoseEdgeFactory'
    module_name: '.prior_pose'

  visual_odometry_edge_factory:
    name: 'visual_odometry_edge_factory'
    type_name: 'VisualOdometryEdgeFactory'
    module_name: '.smart_visual_features'
    search_time_margin: 0.02

  imu_odometry_edge_factory:
    name: 'imu_odometry_edge_factory'
    type_name: 'ImuOdometryFactory'
    module_name: '.imu_preintegration.imu_odometry'
    search_time_margin: 0.01
