package_name: 'moduslam.frontend_manager.edge_factories'

edge_factories:

  prior_pose_edge_factory:
    name: 'prior_pose_edge_factory'
    type_name: 'PriorPoseEdgeFactory'
    module_name: '.prior_pose'

  smart_visual_features_edge_factory:
    name: 'smart_visual_features_edge_factory'
    type_name: 'SmartVisualFeaturesFactory'
    module_name: '.smart_visual_features.factory'
    search_time_margin: 0.02

  imu_odometry_edge_factory:
    name: 'imu_odometry_edge_factory'
    type_name: 'ImuOdometryFactory'
    module_name: '.imu_preintegration.factory'
    search_time_margin: 0.01
