package_name: 'slam.frontend_manager.edge_factories'

edge_factories:

  prior_pose_edge_factory:
    name: 'prior_pose_edge_factory'
    type_name: 'PriorPoseEdgeFactory'
    module_name: '.prior_pose'

  gps_position_edge_factory:
    name: 'gps_position_edge_factory'
    type_name: 'GpsPositionEdgeFactory'
    module_name: '.gps_position'
    search_time_margin: 0.05

  imu_odometry_edge_factory:
    name: 'imu_odometry_edge_factory'
    type_name: 'ImuOdometryFactory'
    module_name: '.imu_preintegration.imu_odometry'
    search_time_margin: 0.01
