[build-system]
requires = [
    'setuptools',
    'wheel',
    'hatchling'
]
build-backend = 'setuptools.build_meta'

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
ignore_missing_imports = true
follow_imports = "normal"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.docformatter]
black = true
inplace = true
docstring-length = [1, 100]
style = "google"
recursive = true

[tool.doc8]
max-line-length = 100
paths = ["docs"]
