[tool.poetry]
name = "moduslam"
version = "0.1.0"
description = "Modular framework for simultaneous localization and mapping."
authors = ["Mark Griguletskii <fatrybl@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
hydra-core = "^1.3.2"
gtsam = "^4.2"
pillow = "^10.3.0"
plum-dispatch = "^2.3.6"
numpy = "^1.26.4"
psutil = "^5.9.8"
kiss-icp = "^0.4.0"
graphviz = "^0.20.3"
colorlog = "^6.8.2"

#======================
# Now open3D is installed with pip, cause poetry has conflicts with legacy open3D code.
#
# TODO: Remove these when Open3D releases >0.18.0 with ML dependencies properly set that is
#   compatible with Poetry. https://github.com/isl-org/Open3D/issues/5747
#   https://github.com/isl-org/Open3D-ML/blob/main/requirements.txt
open3d = "*"
addict = "*"
tqdm = "*"
pyquaternion = "*"
matplotlib = ">=3"
pandas = ">=1.0"
pyyaml = ">=5.4.1"
scikit-learn = ">=0.21"
# ======================
opencv-python = "^4.9.0.80"
transformers = "^4.41.2"
torch = "^2.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"
mypy = "^1.10.0"
black = "^24.4.2"
flake8 = "^7.0.0"
sphinx = "^7.3.7"
pre-commit = "^3.7.1"
types-setuptools = "^70.0.0.20240524"
sphinx-rtd-theme = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.docformatter]
black = true
inplace = true
style = "google"
recursive = true

[tool.doc8]
max-line-length = 100
paths = ["docs"]
ignore = ["D001"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
ignore_missing_imports = true
follow_imports = "normal"
