[build-system]
requires = [
    'setuptools',
    'wheel',
    'hatchling'
]
build-backend = 'setuptools.build_meta'

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
ignore_missing_imports = true
exclude = ['slam.frontend_manager']
follow_imports = "silent"