defaults:
  - /map_factories/base_lidar_map_factory@map_factory
  - /map_loaders/base_lidar_map_loader@map_loader

map_factory:
  map_type: "lidar_pointcloud"
  min_range: 3
  max_range: 100

map_loader:
  directory: "/home/mark/Desktop/PhD/ModuSLAM/"
