defaults:
  - /sensors/kaist/lidar_3D_right@sensors_factory.sensors
  - /sensors/kaist/lidar_3D_left@sensors_factory.sensors
  - /sensors/kaist/imu@sensors_factory.sensors
  - edge_factories_initializers/lidar_imu_odometry@edge_factories_initializer
  - handlers_factories/2_lidar_imu_odometry@handlers_factory
  - state_analyzers_factories/2_lidar_imu@state_analyzers_factory
