defaults:
  - /sensors/lidar_3D_right@sensors_factory.sensors
  - /sensors/lidar_3D_left@sensors_factory.sensors
  - /sensors/imu@sensors_factory.sensors
  - /sensors/vrs_gps@sensors_factory.sensors

  - edge_factories_initializers/lidar_imu_vrs@edge_factories_initializer
  - handlers_factories/2_lidar_imu_vrs@handlers_factory
  - state_analyzers_factories/2_lidar_imu_vrs@state_analyzers_factory
