defaults:
  - /handlers/base_kiss_icp_odometry@handlers_factory.handlers.kiss_icp_odometry

handlers_factory:
  package_name: 'slam.frontend_manager.handlers'

  handlers:

    kiss_icp_odometry:
      name: "kiss_icp_odometry"
      type_name: "ScanMatcher"
      module_name: ".pointcloud_matcher"

    imu_preprocessor:
      name: "imu_preprocessor"
      type_name: "ImuDataPreprocessor"
      module_name: ".imu_data_preprocessor"
