defaults:
  - lidar_imu
  - /sensors/vrs_gps@sensors_factory.sensors
  - edge_factories_initializers/lidar_imu_vrs@edge_factories_initializer
  - handlers_factories/lidar_imu_vrs@handlers_factory
  - state_analyzers_factories/lidar_imu_vrs@state_analyzers_factory
