defaults:
  - lidar
  - /sensors/imu@sensors_factory.sensors
  - edge_factories_initializers/lidar_inertial_odometry@edge_factories_initializer
  - handlers_factories/lidar_imu_odometry@handlers_factory
  - state_analyzers_factories/lidar_imu@state_analyzers_factory
