defaults:
  - /sensors/ros2/imu@sensors_factory.sensors
#  - /sensors/ros2/lidar_3D_left@sensors_factory.sensors
#  - /sensors/base_stereo_camera@sensors_factory.sensors
  - edge_factories_initializers/lidar_imu_odometry@edge_factories_initializer
  - handlers_factories/lidar_imu_odometry@handlers_factory
  - state_analyzers_factories/lidar_imu@state_analyzers_factory
