defaults:
  - /base_factory
  - dataset: kaist_urban
  - _self_

regime:
  name: "TimeLimit"
  # Urban-27
  start: 1544681686136785765
  stop: 1544681690187941000

batch_memory_percent: 90.0

# 5 secs movement
