defaults:
  - /base_pose@pose1
  - _self_


#Urban-26
pose1:
  timestamp: 1544580754879777642
  measurement: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  noise_covariance: [ 1e-1, 1e-1, 1e-1, 1e1, 1e1, 1e1 ] # x, y, z, roll, pith, yaw
