defaults:
  - /base_pose@pose1
  #  - /base_pose@pose2
  #  - /base_linear_velocity@velocity1
  #  - /base_imu_bias@bias1
  - _self_

pose1:
  timestamp: 1544581170279399000
  noise_covariance: [ 1e-3, 1e-3, 1e-3, 1e-3, 1e-3, 1e-3 ] # x, y, z, roll, pith, yaw

#pose2:
#  timestamp: 1544581170343974000
#  measurement: [ 0.05, 0.0, 0.0, 0.0, 0.0, 0.0 ]
#  noise_covariance: [ 1e-3, 1e-3, 1e-3, 1e-3, 1e-3, 1e-3 ] # x, y, z, roll, pith, yaw
#
#velocity1:
#  timestamp: 1544581170279399000
#  noise_covariance: [ 1e-0, 1e-1, 1e-2 ] # Vx, Vy, Vz
#  measurement: [ 1.1, 0, 0 ]

#bias1:
#  timestamp: 1544581170279399000
#  noise_covariance: [ 1e-1, 1e-1, 1e-1, 1e-1, 1e-1, 1e-1 ] # b_a_x, b_a_y, b_a_z, b_g_roll, b_g_pith, b_g_yaw
#  measurement: [ 0e-1, 0e-1, 0e-1, 0e-1, 0e-1, 0e-1 ]
