defaults:
  - /base_pose@pose1
  #  - /base_pose@pose2
  #  - /base_position@position1
  #  - /base_pose@pose2
  - /base_linear_velocity@velocity1
  #  - /base_imu_bias@bias1
  - _self_

#pose1:
#  timestamp: 1544581170279399000
#  measurement: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
#  noise_covariance: [ 1e-2, 1e-2, 1e-2, 1e-2, 1e-2, 1e-2 ] # x, y, z, roll, pith, yaw

#Urban-26
#pose1:
#  timestamp: 1544580980454216000
#  #  timestamp: 1544677152006678000
#  measurement: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
#  noise_covariance: [ 1e-1, 1e-1, 1e-1, 1e-1, 1e-1, 1e-1 ] # x, y, z, roll, pith, yaw

#Urban-30
pose1:
  timestamp: 1544682279133415000
  measurement: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  noise_covariance: [ 1e-1, 1e-1, 1e-1, 1e0, 1e0, 1e0 ] # x, y, z, roll, pith, yaw

velocity1:
  timestamp: 1544682279133415000
  noise_covariance: [ 1e-2, 1e-2, 1e-2 ] # Vx, Vy, Vz
  measurement: [ 0, 0, 0 ]

#pose2:
#  timestamp: 1544677161230055000
#  measurement: [ 0.0, 0.0, 0.0, 0.0, 0.0, 1.8 ]
#  noise_covariance: [ 1e-1, 1e-1, 1e-1, 1e0, 1e0, 1e0 ] # x, y, z, roll, pith, yaw

#position1:
#  timestamp: 1544581120850164000
#  noise_covariance: [ 1e-2, 1e-2, 1e-2 ] # x, y, z
#  measurement: [ 0.0, 0.0, 0.0 ]

#pose2:
#  timestamp: 1544581170343974000
#  measurement: [ 0.05, 0.0, 0.0, 0.0, 0.0, 0.0 ]
#  noise_covariance: [ 1e-3, 1e-3, 1e-3, 1e-3, 1e-3, 1e-3 ] # x, y, z, roll, pith, yaw

#velocity1:
#  timestamp: 1544581120850164000
#  noise_covariance: [ 1e-0, 1e-0, 1e-0 ] # Vx, Vy, Vz
#  measurement: [ 0.8, 0, 0 ]


#bias1:
#  timestamp: 1544581170279399000
#  noise_covariance: [ 1e-1, 1e-1, 1e-1, 1e-1, 1e-1, 1e-1 ] # b_a_x, b_a_y, b_a_z, b_g_roll, b_g_pith, b_g_yaw
#  measurement: [ 0e-1, 0e-1, 0e-1, 0e-1, 0e-1, 0e-1 ]
