defaults:
  - /base_pose@pose1
  - /base_linear_velocity@velocity1
  - _self_


#Urban-26
pose1:
  timestamp: 1544581167556220000
  measurement: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  noise_covariance: [ 1e-1, 1e-1, 1e-1, 1e1, 1e1, 1e1 ] # x, y, z, roll, pith, yaw

velocity1:
  timestamp: 1544581167556220000
  measurement: [ 4.5, 0.0, 0.0 ]
  noise_covariance: [ 1e0, 1e-1, 1e-1 ] # x, y, z
