defaults:
  #  - /base_pose@pose1
  #  - /base_linear_velocity@velocity1
  - _self_


#Urban-26
#pose1:
#  timestamp: 1544581170279399000
#  measurement: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
#  noise_covariance: [ 1e-1, 1e-1, 1e-1, 1e1, 1e1, 1e1 ] # x, y, z, roll, pith, yaw
#
#velocity1:
#  timestamp: 1544581170279399000
#  measurement: [ 4.0, 0.0, 0.0 ]
#  noise_covariance: [ 1e-1, 1e-1, 1e-1 ] # x, y, z

#pose1:
#  timestamp: 1544581126870152013
#  measurement: [ 0.0, 0.0, 0.0, 0.0, 0.0, 1.0 ]
#  noise_covariance: [ 1e-1, 1e-1, 1e-1, 1e1, 1e1, 1e1 ] # x, y, z, roll, pith, yaw

#velocity1:
#  timestamp: 1544581126870152013
#  measurement: [ 5.0, 2.0, 0.0 ]
#  noise_covariance: [ 1e0, 1e0, 1e-1 ] # x, y, z
