defaults:
  - /base_ros2_s3e_dataset

directory: "/home/mark/Downloads/s3e_dataset"

# names must match the ones in the Sensors Factory config.
sensor_topic_mapping:
  "left_camera": "/Alpha/left_camera/compressed"
  "right_camera": "/Alpha/right_camera/compressed"
  "Alpha_imu": "/Alpha/imu/data"
  "vlp_16": "/Alpha/velodyne_points"
