package_name: "slam.frontend_manager.graph_builder.state_analyzers"

analyzers:

  lidars_imu_gps_state_analyzer:
    name: "lidars_imu_gps_state_analyzer"
    type_name: "LidarsImuGpsAnalyzer"
    module_name: ".lidars_imu_gps"
