package_name: "slam.frontend_manager.graph_builder.state_analyzers"

analyzers:

  lidar_gps_state_analyzer:
    name: "lidar_gps_state_analyzer"
    type_name: "LidarGpsAnalyzer"
    module_name: ".lidar_gps"
