defaults:
  - /datasets/base_kaist_dataset@batch_factory.dataset
  - /regimes/base_regime@batch_factory.regime

batch_factory:
  dataset:
    directory: "/home/mark/Downloads/urban30-gangnam/"

  regime:
    name: "TimeLimit"
    start: 1544676739798931000
    stop: 1544676740000631000

  memory:
    batch_memory: 100.0
