defaults:
  - /datasets/base_kaist_dataset@batch_factory.dataset
  - /regimes/base_regime@batch_factory.regime

batch_factory:
  dataset:
    directory: "/home/mark/Desktop/datasets/kaist/urban30-gangnam/"

  regime:
    name: "TimeLimit"
    start: 1544676739496345000
    stop: 1544676739698053000

  memory:
    batch_memory: 100.0
