defaults:
  # - /datasets/base_kaist_dataset@batch_factory.dataset
  - /datasets/base_ros2_dataset@batch_factory.dataset
  - /regimes/base_regime@batch_factory.regime

batch_factory:
  dataset:
    # directory: "/home/felipezero/Projects/mySLAM_data/urban-26"
    directory: "/home/felipezero/Projects/mySLAM_data/20231102_kia/rosbag2_2024_1713939297"
    # directory: "/media/mark/New Volume/datasets/kaist/urban-26"

  regime:
    name: "TimeLimit"
    start: 1544581174111995000
    stop: 1544581195292098000

  memory:
    batch_memory: 100.0

#    start: 1544581174111995000
#    stop: 1544581174479101000

# for urban-30
#    start: 1544677010043554000
#    stop: 1544677020028534000
