defaults:
  - /datasets/base_ros2_dataset@batch_factory.dataset
  - /regimes/base_data_regime@batch_factory.regime

batch_factory:

  dataset:
#    directory: "/home/lab/Desktop/rosbag2_2023_11_02-12_18_16"
    directory: "/home/lab/ModuSLAM/tests_data/datasets/ros2/test_rosbag_100"
#    directory: "/home/lab/r2bdataset2023_3/r2b_lounge"
    sensors_table: # Mapping of sensor names to their corresponding topic names
      stereo_camera_left: "left"
      stereo_camera_right: "right"
      imu: "xsens"
      lidar_left: "vlp16l"
      lidar_right: "vlp16r"
      lidar_center: "vlp32c"

    topics_table: # Mapping of sensor names to their data types
      stereo_camera_left: "Image"
      stereo_camera_right: "Image"
      imu: "Imu"
      lidar_left: "PointCloud2"
      lidar_right: "PointCloud2"
      lidar_center: "PointCloud2"

#    sensors_table:
#      stereo_camera_left: "d455_1_left_ir_camera_info"
#      stereo_camera_right: "d455_1_right_ir_image"
#      imu: "d455_1_imu"
#      lidar_left: "pandar_xt_32_0_lidar"
#      lidar_right: "vlp16r"
#      lidar_center: "vlp32c"

  regime:
    name: "TimeLimit"
    start: 1698927496694033807
    stop:  1698927497190095250

  batch_memory_percent: 100.0

# for images:
#    start: 1544581174020425974
#    stop: 1544581174920112387

# for lidar
#    start: 1544581174111995000
#    stop: 1544581195292098000

# for urban-30
#    start: 1544677010043554000
#    stop: 1544677020028534000
