defaults:
  - /datasets/base_tum_vie_dataset@batch_factory.dataset
  - /regimes/base_data_regime@batch_factory.regime

batch_factory:
  dataset:
    directory: "/media/mark/New Volume/datasets/tum/visual_inertial_event/loop_floor_0"
  regime:
    name: "TimeLimit"
    start: 4.418806189999999478e+06
    stop: 4.468949240999999456e+06

  batch_memory_percent: 100.0
