# % of RAM to be used
memory_analyzer:
  "data_batch": 50
  "graph": 30

# simple filter for raw data
data_filter:
  use_filter: false

# path to directory with data files
data:
  dataset_type: "kaist"
  dataset_directory: "/home/oem/Downloads/urban18-highway/"
