# % of RAM to be used for graph storage. Adequate values in range of [10-30]
memory_analyzer:
  "graph": 30

# simple filter for raw data
data_filter:
  use_filter: false

# path to directory with data files
data:
  dataset_type: "kaist" #possiple values kaist, ros1
  dataset_directory: "/home/oem/Downloads/urban18-highway/" #"/home/ilia/mySLAM/data/rosbag" 
