# names of topics in .bag file or headers in .csv or whatever
ros1_reader:
  used_topics:
    imu: "sensors/imu_data/imu"
    encoder: "sensors/lidar"
    stereo": "sensors/realsense/stereo"

kaist_reader:
  # sensor names in data_stamp.csv
used_sensors:
  [
    encoder,
    imu,
    altimeter,
    fog,
    sick_middle,
    sick_back,
    velodyne_right,
    velodyne_left,
    stereo,
  ]
