# position (row number) in file to start from
start_position: start
stop_position: stop

# names of topics in .bag file or headers in .csv or whatever
ros1_reader:
  used_messages:
    "sensors/imu_data/imu",
    "sensors/gnss/status",
    "sensors/gnss/position"
    "sensors/lidar/left",
    "sensors/lidar/right",
    "sensors/camera/rgb_image"

csv_reader:
  new_line: ""
  delimiter: ","
  quotechar: "|"
  used_messages:
    time: [0, 1]
    imu: [1, 7]
    wheel_odom: [7, 10]
    gps_pose: [10, 13]

kaist_reader:
  asdasd: adasdas
