# names of topics in .bag file or headers in .csv or whatever
ros1_reader:
  used_topics:
    imu: "/imu_data"
    gps: "/position_gps"
    lidar_sick_back": "/scan"

kaist_reader:
  # sensor names in data_stamp.csv
used_sensors:
  [
    imu,
    gps
  ]
