start_position: start
stop_position: stop

# names of topics in .bag file or headers in .csv or whatever
ros1_reader:
  used_sensors:
    - "/imu_data": "imu"
    - "/position_gps": "gps"
    - "/scan": "lidar"


csv_reader:
  new_line: ""
  delimiter: ","
  quotechar: "|"
  used_messages:
    time: [0, 1]
    imu: [1, 7]
    wheel_odom: [7, 10]
    gps_pose: [10, 13]

kaist_reader:
  # one_file_sensors: [imu, fog, gps, vrs, altimeter, encoder]
