# % of RAM to be used for graph storage. Adequate values in range of [10-30]
memory_analyzer:
  "graph": 30

# simple filter for raw data
data_filter:
  use_filter: false

# path to directory with data files
data:
  dataset_type: "kaist" #  "ros1"  
  dataset_directory: "/home/oem/Downloads/urban18-highway/" # "/home/ilia/mySLAM/data/rosbag"
  timestamp_limits:
    start: 1234
    stop: 1234

# supported sensors` types: imu, camera, lidar, gps, encoder ...
sensors:
  fog:
    type: "fog"
    config: "fog.yaml"

  imu:
    type: "imu"
    config: "imu.yaml"

  encoder:
    type: "encoder"
    config: "encoder.yaml"

  gps:
    type: "gps"
    config: "gps.yaml"

  vrs:
    type: "vrs_gps"
    config: "vrs.yaml"

  altimeter:
    type: "altimeter"
    config: "altimeter.yaml"

  sick_back:
    type: "lidar_2D"
    config: "sick_back.yaml"

  sick_middle:
    type: "lidar_2D"
    config: "sick_middle.yaml"

  velodyne_left:
    type: "lidar_3D"
    config: "velodyne_left.yaml"

  velodyne_right:
    type: "lidar_3D"
    config: "velodyne_right.yaml"

  stereo:
    type: "stereo_camera"
    config: "stereo.yaml"

  altimeter:
    type: "altimeter"
    config: "altimeter.yaml"

  gps:
    type: "gps"
    config: "gps.yaml"

  