# % of RAM to be used for graph storage. Adequate values in range of [10-30]
memory_analyzer:
  "graph": 20

# simple filter for raw data
data_filter:
  use_filter: false

# path to directory with data files
data:
  dataset_type: "kaist"
  dataset_directory: "/home/oem/Downloads/urban18-highway/"
