defaults:
  - /base_factory
  - dataset: kaist_urban
  - _self_

regime:
  name: "TimeLimit"
  # Urban-27
  start: 1544681555137376000
  stop: 1544681562191535000

batch_memory_percent: 90.0

# 7 secs movement
