defaults:
  - /base_factory
  - dataset: kaist_urban
  - _self_

regime:
  name: "TimeLimit"
  # Urban-33
  start: 1544681555131464000
  stop: 1544681562096557000

batch_memory_percent: 90.0

# 7 secs movement
