defaults:
  - /base_pose@pose1
  #  - /base_linear_velocity@priors.velocity1
  - _self_

pose1:
  timestamp: 1544581170279399000
  noise_covariance: [ 1e-3, 1e-3, 1e-3, 1e-3, 1e-3, 1e-3 ] # x, y, z, roll, pith, yaw

#  velocity1:
#    timestamp: 1544581170279399000
#    noise_covariance: [ 1e-2, 1e-2, 1e-2 ] # Vx, Vy, Vz
#    measurement: [ 0, 0, 0 ]
