defaults:
  - 2_lidar_imu

graph_builder:

  element_distributor:
    sensor_handlers_table:
      vrs: [ 'vrs_gps_preprocessor' ]

  candidate_factory:

    handler_state_analyzer_table:
      kiss_icp_odometry_1: 'lidars_imu_gps_state_analyzer'
      kiss_icp_odometry_2: 'lidars_imu_gps_state_analyzer'
      imu_preprocessor: 'lidars_imu_gps_state_analyzer'
      vrs_gps_preprocessor: 'lidars_imu_gps_state_analyzer'


  graph_merger:

    handler_edge_factory_table:
      vrs_gps_preprocessor: 'gps_position_edge_factory'


graph_initializer: null

#  priors:
#    initial_pose:
#      timestamp: 1544580713878047885 # timestamp of first vrs_gps message.
#      vertex_type: "Pose"
#      edge_factory_name: "prior_pose_edge_factory"
#      measurement: [ 330096.41562497173436, 4118151.5854207249358, 35.731699, 0, 0, 2.5 ]
#      measurement_noise_covariance: [ 1, 1, 1, 1, 1, 1 ]
#      file_path: "configs/frontend_manager/kaist.yaml"
