graph_builder:

  name: 'LidarMapBuilder'

  element_distributor:
    sensor_handlers_table:
      velodyne_right: [ 'kiss_icp_odometry' ]

  graph_merger:
    handler_edge_factory_table:
      kiss_icp_odometry: 'lidar_odometry_edge_factory'

  candidate_factory:
    handler_state_analyzer_table:
      kiss_icp_odometry: 'lidar_odometry_state_analyzer'

graph_initializer:
  priors:
    initial_pose:
      timestamp: 1544581174277398000 # timestamp of first VLP_right scan from batch_factory.yaml
      vertex_type: "Pose"
      edge_factory_name: "prior_pose_edge_factory"
      measurement: [ 0,0,0,0,0,0 ]
      measurement_noise_covariance: [ 0.01, 0.01, 0.01, 0.01, 0.01, 0.01 ]
      file_path: "configs/frontend_manager/config.yaml"
