defaults:
  - lidar_imu

graph_builder:

  element_distributor:
    sensor_handlers_table:
      vrs: [ 'vrs_gps_preprocessor' ]

  candidate_factory:

    handler_state_analyzer_table:
      kiss_icp_odometry: 'lidar_imu_state_analyzer'
      imu_preprocessor: 'lidar_imu_state_analyzer'
      vrs_gps_preprocessor: 'gps_state_analyzer'


  graph_merger:

    handler_edge_factory_table:
      vrs_gps_preprocessor: 'gps_position_edge_factory'

graph_initializer:

  priors:
    initial_pose:
      timestamp: 1544580712879337145
      vertex_type: "Pose"
      edge_factory_name: "prior_pose_edge_factory"
      measurement: [ 330096.41, 4118151.58, 35.73, 0.0, 0.0, 2.8 ]
      measurement_noise_covariance: [ 1, 1, 1, 1.5, 1.5, 1.5 ]
      file_path: "configs/frontend_manager/kaist.yaml"
