defaults:
  - lidar

graph_builder:

  element_distributor:
    sensor_handlers_table:
      vrs: [ 'vrs_gps_preprocessor' ]

  candidate_factory:

    handler_state_analyzer_table:
      kiss_icp_odometry: 'lidar_gps_state_analyzer'
      vrs_gps_preprocessor: 'lidar_gps_state_analyzer'


  graph_merger:

    handler_edge_factory_table:
      vrs_gps_preprocessor: 'gps_position_edge_factory'

graph_initializer: null

#  priors:
#    initial_pose:
#      timestamp: 1544580715865638000 # timestamp of first vrs_gps message.
#      vertex_type: "Pose"
#      edge_factory_name: "prior_pose_edge_factory"
#      measurement: [ 330096.41562497173436, 4118151.5854207249358, 35.731699, 0, 0, 0 ]
#      measurement_noise_covariance: [ 0.1, 0.1, 0.1, 1, 1, 1 ]
#      file_path: "configs/frontend_manager/lidar.yaml"
