defaults:
  - lidar

graph_builder:

  element_distributor:
    sensor_handlers_table:
      imu: [ 'imu_preprocessor' ]

  candidate_factory:

    handler_state_analyzer_table:
      kiss_icp_odometry: 'lidar_imu_state_analyzer'
      imu_preprocessor: 'lidar_imu_state_analyzer'


  graph_merger:

    handler_edge_factory_table:
      imu_preprocessor: 'imu_odometry_edge_factory'

graph_initializer:

  priors:
    initial_pose:
      timestamp: 1544581170279399000 # timestamp of first VLP_right scan from data_manager/kaist.yaml
      vertex_type: "Pose"
      edge_factory_name: "prior_pose_edge_factory"
      measurement: [ 0,0,0,0,0,0 ]
      measurement_noise_covariance: [ 0.5, 0.5, 0.5, 1, 1, 1 ]
      file_path: "configs/frontend_manager/kaist.yaml"
