lidar_odometry_state_analyzer:

  name: "lidar_odometry_state_analyzer"
  type_name: "LidarOdometryStateAnalyzer"
  module_name: ".lidar_odometry"
  handler_name: "kiss_icp_odometry"

#imu_preintegration:
#
#  name: 'imu_preintegration'
#  type_name: 'ImuPreintegrator'
#  module_name: '.imu_preintegration'
#  handler_name: "imu_odometry"
