defaults:
  - stereo

graph_builder:

  element_distributor:
    sensor_handlers_table:
      imu: [ 'imu_preprocessor' ]

  candidate_factory:

    handler_state_analyzer_table:
      camera_features_detector: 'visual_inertial_odometry_state_analyzer'
      imu_preprocessor: 'visual_inertial_odometry_state_analyzer'


  graph_merger:

    handler_edge_factory_table:
      imu_preprocessor: 'imu_odometry_edge_factory'
      camera_features_detector: 'smart_visual_features_edge_factory'

graph_initializer:

  priors:

    first_pose:
      timestamp: 3618556327 # timestamp of first VLP_right scan from data_manager/kaist.yaml
      vertex_type: "Pose"
      edge_factory_name: "prior_pose_edge_factory"
      measurement: [ 0,0,0,0,0,0 ]
      measurement_noise_covariance: [ 0.5, 0.5, 0.5, 1, 1, 1 ]
      file_path: "configs/frontend_manager/stereo_imu.yaml"

    second_pose:
      timestamp: 3668542882 # timestamp of first VLP_right scan from data_manager/kaist.yaml
      vertex_type: "Pose"
      edge_factory_name: "prior_pose_edge_factory"
      measurement: [ 0,0,0,0,0,0 ]
      measurement_noise_covariance: [ 0.5, 0.5, 0.5, 1, 1, 1 ]
      file_path: "configs/frontend_manager/stereo_imu.yaml"
