graph_builder:

  name: 'PointcloudMapBuilder'

  element_distributor:

    sensor_handlers_table:
      stereo: [ 'visual_odometry' ]

  candidate_factory:

    handler_state_analyzer_table:
      visual_odometry: 'visual_odometry_state_analyzer'

  graph_merger:

    handler_edge_factory_table:
      visual_odometry: 'visual_odometry_edge_factory'

graph_initializer:

  priors:
    initial_pose:
      timestamp: 3618556327
      vertex_type: "Pose"
      edge_factory_name: "prior_pose_edge_factory"
      measurement: [ 0,0,0,0,0,0 ]
      measurement_noise_covariance: [ 0.5, 0.5, 0.5, 1, 1, 1 ]
      file_path: "configs/frontend_manager/kaist.yaml"
