graph_builder:

  name: 'PointcloudMapBuilder'

  element_distributor:

    sensor_handlers_table:
      stereo: [ 'camera_features_detector' ]

  candidate_factory:

    handler_state_analyzer_table:
      camera_features_detector: 'visual_features_state_analyzer'

  graph_merger:

    handler_edge_factory_table:
      camera_features_detector: 'smart_visual_features_edge_factory'

graph_initializer:

  priors:

    first_pose:
      timestamp: 4218859222 # timestamp of first VLP_right scan from data_manager/kaist.yaml
      vertex_type: "Pose"
      edge_factory_name: "prior_pose_edge_factory"
      measurement: [ 0,0,0,0,0,0 ] # x,y,z,roll,pitch,yaw
      measurement_noise_covariance: [ 0.01, 0.01, 0.01, 0.01, 0.01, 0.01 ]
      file_path: "configs/frontend_manager/stereo_imu.yaml"

    second_pose:
      timestamp: 4268740779 # timestamp of first VLP_right scan from data_manager/kaist.yaml
      vertex_type: "Pose"
      edge_factory_name: "prior_pose_edge_factory"
      measurement: [ 0,0,0.03,0,0,0.0 ] # x,y,z,roll,pitch,yaw
      measurement_noise_covariance: [ 1, 1, 1, 1, 1, 1 ]
      file_path: "configs/frontend_manager/stereo_imu.yaml"
