defaults:
  - /base_pose@pose1
  - _self_


pose1:
  timestamp: 1559194794098995359
  measurement: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
  noise_covariance: [ 1e1, 1e1, 1e1, 1e1, 1e1, 1e1 ] # x, y, z, roll, pith, yaw
