defaults:
  - /base_factory
  - dataset: kaist_urban
  - _self_

regime:
  name: "TimeLimit"
  # Urban-33
  start: 1544681590135154000
  stop: 1544681600215064000

batch_memory_percent: 90.0

# 10 secs movement
