defaults:
  - /sensors/base_imu@imu

imu:
  name: "imu"
  tf_base_sensor: [
    [ 1.0, 0.0, 0.0, -0.07 ],
    [ 0.0, 1.0, 0.0, 0.0 ],
    [ 0.0, 0.0, 1.0, 1.7 ],
    [ 0.0, 0.0, 0.0, 1.0 ]
  ]
  accelerometer_noise_covariance: [
    [ 1e-3, 0.0, 0.0 ],
    [ 0.0, 1e-3, 0.0 ],
    [ 0.0, 0.0, 1e-3 ]
  ]
  gyroscope_noise_covariance: [
    [ 1e-3, 0.0, 0.0 ],
    [ 0.0, 1e-3, 0.0 ],
    [ 0.0, 0.0, 1e-3 ]
  ]
  accelerometer_bias_noise_covariance: [
    [ 1e-4, 0.0, 0.0 ],
    [ 0.0, 1e-4, 0.0 ],
    [ 0.0, 0.0, 1e-4 ]
  ]
  gyroscope_bias_noise_covariance: [
    [ 1e-4, 0.0, 0.0 ],
    [ 0.0, 1e-4, 0.0 ],
    [ 0.0, 0.0, 1e-4 ]
  ]
  integration_noise_covariance:
    [
      [ 1e-6, 0.0, 0.0 ],
      [ 0.0, 1e-6, 0.0 ],
      [ 0.0, 0.0, 1e-6 ]
    ]

