defaults:
  - _self_ # default hydra config to override job_logging and hydra_logging
  - structured_schema_config # base Structured Schema Validation

  - setup_manager:
      - sensors_factory
      - handlers_factory
      - state_analyzers_factory
      - edge_factories_initializer

  - data_manager:
      - batch_factory

  - frontend_manager:
      - config

  - map_manager:
      - config

  - override hydra/hydra_logging: none
  - override hydra/job_logging: colorlog

hydra:
  output_subdir: null
  run:
    dir: .
