defaults:
  #Kaist Urban:
  #  - /sensors/kaist/stereo_camera@_here_
  #  - /sensors/kaist/imu@_here_
  #  - /sensors/kaist/lidar_3D_left@_here_
  #  - /sensors/kaist/lidar_3D_right@_here_
  #  - /sensors/kaist/vrs_gps@_here_
  # TIM VIE:
  #  - /sensors/tum_vie/stereo_camera@_here_
  #  - /sensors/tum_vie/imu@_here_

  # ROS2 S3E:
  #  - /sensors/s3e/alpha/imu@_here_
  - /sensors/s3e/alpha/lidar@_here_
  #  - /sensors/s3e/alpha/camera_left@_here_
  #  - /sensors/s3e/alpha/camera_right@_here_
  #  - /sensors/s3e/alpha/rtk@_here_
  - _self_
