name : camera1
type : rgb_camera


# extrinsic parameters
tf: 
 [1, 0, 0, 0
  0, 1, 0, 0
  0, 0, 1, 0
  0, 0, 0, 1]


#intrinsic parameters

focal_distance: 0.01

measurement_covariance: 
 [1e-5, 0, 0
  0, 1e-5, 0, 
  0, 0, 1e-5]