from tests.moduslam.data_manager.batch_factory.readers.kaist_urban.scenarios.data import (
    all_sensors,
    altimeter,
    dataset_cfg,
    el2,
    el3,
    el5,
    el8,
    el10,
    el12,
    el14,
    el19,
    el22,
    el23,
    el24,
    el25,
    elements,
    imu,
    lidar2D_back,
    lidar2D_middle,
    sensors_factory_config1,
    sensors_factory_config2,
    sensors_factory_config3,
    sensors_factory_config4,
    sensors_factory_config5,
    sensors_factory_config6,
    stereo,
    stream,
    timelimit1,
    timelimit2,
    timelimit3,
    timelimit4,
    timelimit5,
    timelimit6,
    timelimit7,
)

valid_stream_scenarios = (
    (sensors_factory_config1, dataset_cfg, stream, all_sensors, elements),
    (sensors_factory_config2, dataset_cfg, stream, [imu, imu, imu], [el3, el10, el23]),
    (
        sensors_factory_config3,
        dataset_cfg,
        stream,
        [lidar2D_back, lidar2D_back],
        [el2, el12],
    ),
    (
        sensors_factory_config4,
        dataset_cfg,
        stream,
        [stereo, stereo, stereo],
        [el19, el22, el24],
    ),
    (
        sensors_factory_config5,
        dataset_cfg,
        stream,
        [lidar2D_middle, lidar2D_middle, lidar2D_middle],
        [el5, el14, el25],
    ),
    (
        sensors_factory_config5,
        dataset_cfg,
        stream,
        [lidar2D_middle, imu, lidar2D_middle, stereo],
        [el5, None, el14, None],
    ),
)

valid_timelimit_scenarios = (
    (
        sensors_factory_config1,
        dataset_cfg,
        timelimit1,
        all_sensors,
        elements,
    ),
    (
        sensors_factory_config2,
        dataset_cfg,
        timelimit2,
        [imu, imu, imu],
        [el3, el10, el23],
    ),
    (
        sensors_factory_config3,
        dataset_cfg,
        timelimit3,
        [lidar2D_back, lidar2D_back],
        [el2, el12],
    ),
    (
        sensors_factory_config4,
        dataset_cfg,
        timelimit4,
        [stereo, stereo, stereo],
        [el19, el22, el24],
    ),
    (
        sensors_factory_config5,
        dataset_cfg,
        timelimit5,
        [lidar2D_middle, lidar2D_middle, lidar2D_middle],
        [el5, el14, el25],
    ),
    (sensors_factory_config3, dataset_cfg, timelimit2, [lidar2D_back], [el12]),
    (
        sensors_factory_config4,
        dataset_cfg,
        timelimit2,
        [stereo, stereo],
        [el19, el22],
    ),
    (sensors_factory_config6, dataset_cfg, timelimit6, [imu, altimeter], [el3, el8]),
    (
        sensors_factory_config6,
        dataset_cfg,
        timelimit6,
        [imu, altimeter, stereo, imu],
        [el3, el8, None, None],
    ),
    (
        sensors_factory_config6,
        dataset_cfg,
        timelimit7,
        [imu, altimeter, stereo, imu],
        [el3, el8, None, el10],
    ),
)

kaist2 = (
    *valid_stream_scenarios,
    *valid_timelimit_scenarios,
)
