name: Build Sphinx Docs

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # or specify your exact version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

      - name: Generate API docs and build
        run: |
          sphinx-apidoc -f -o docs/source/ ./src/
          cd docs
          make clean html
