name: Build Documentation

on:
  push:
    branches: [ '**' ]  # All branches
  pull_request:
    branches: [ main, develop ]  # Optional PR handling
  workflow_dispatch:  # Manual trigger

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints

      - name: Build documentation
        working-directory: ./docs
        run: |
          sphinx-apidoc -f -o source/ ../src/
          make clean html

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/_build/html
