name: Run Tests

on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: Install dependencies
        run: |
          poetry install

      - name: Install pip dependencies
        run: |
          pip install open3d gtsam

      - name: Set Test Data Directory
        run: echo "TEST_DATA_DIR=$(pwd)/tests_data" >> $GITHUB_ENV

      - name: Run PhD tests
        run: |
          poetry run pytest src/tests
