name: Run tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-venv \
            python3-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry to Use the Correct Python
        run: poetry env use $(which python)

      - name: Install project dependencies with Poetry
        run: poetry install --only=main,test

      - name: Set Test Data Directory
        run: echo "SRC_DIR=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Run tests
        run: |
          poetry run pytest tests
